---
- hosts: all

  vars:
    http_port: "{{ port }}"
    domain: "example.com"

  tasks:
    - name: Install Git package
      become: yes
      apt: name=git update_cache=yes state=latest

    - name: Add PHP 7 PPA repository
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install PHP CLI
      become: true
      apt:
        name: php7.2-cli
        state: latest

    - name: Install PHP XML
      become: true
      apt:
        name: php7.2-xml
        state: latest

    - name: Install PHP INTL
      become: true
      apt:
        name: php7.2-intl
        state: latest

    - name: Install low-level utilities
      become: true
      apt:
        name: "{{ item }}"
      with_items:
        - zip
        - unzip

    - name: Download Composer
      script: scripts/install_composer.sh

    - name: Move Composer globally to be able to execute commands
      become: true
      command: mv composer.phar /usr/local/bin/composer

    - name: Set permissions on Composer
      become: true
      file:
        path: /usr/local/bin/composer
        mode: "a+x"

    - name: Install apache
      become: yes
      apt: name=apache2 update_cache=yes state=latest
      notify:
        - restart apache2

    - name: Enable mod_rewrite
      become: yes
      apache2_module: name=rewrite state=present
  
    - name: Remove default Apache port.conf
      become: yes
      file:
        path: /etc/apache2/ports.conf
        state: absent

    - name: Remove default Apache default.conf
      become: yes
      file:
        path: /etc/apache2/sites-available/000-default.conf
        state: absent

    - name: Add new Apache port.conf from template
      become: yes
      template:
        src: templates/ports.conf.j2
        dest: /etc/apache2/ports.conf

    - name: Add new Apache default.conf from template
      become: yes
      template:
        src: templates/000-default.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf

    - name: Remove default website directory
      become: yes
      file:
        path: /var/www/html
        state: absent

    - name: Git retrieve new website
      become: yes
      git:
        repo: "{{ app_repo }}"
        dest: /var/www/{{ app_name }}
      notify:
        - restart apache2

    - name: Updating rights for website directory
      become: yes
      file:
        path: /var/www/{{ app_name }}
        state: directory
        mode: 0777
        recurse: yes

    - name: Updating rights for website cache
      become: yes
      file:
        path: /var/www/{{ app_name }}/var/cache
        state: directory
        mode: 0777
        recurse: yes

    - name: Run ls.sh and output "ls /"
      command: ls /var/www/{{ app_name }}
      register: out

    - debug: var=out.stdout_lines

    - name: Install dependencies of Symfony website
      composer:
        command: install
        working_dir: /var/www/{{ app_name }}
        prefer_dist: yes

  handlers:
    - name: restart apache2
      become: yes
      service: name=apache2 state=restarted

    